# https://github.com/actions/labeler
benchmark:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - benchmark/**/*
build:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - Dockerfile
              - Doxyfile
              - Makefile
              - Rakefile
              - appveyor.yml
              - build_config.rb
              - build_config/**/*
              - docker-compose.yml
              - lib/**/*
              - minirake
              - tasks/**/*
              - .dockerignore
              - .pre-commit-config.yaml
              - .travis.yml
              - .yardopts
core:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - include/**/*
              - mrblib/**/*
              - src/**/*
              - test/**/*
doc:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - CONTRIBUTING.md
              - LEGAL
              - LICENSE
              - NEWS
              - README.md
              - SECURITY.md
              - TODO.md
              - doc/**/*
              - examples/**/*
github:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .github/**/*
miscellaneous:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .editorconfig
              - .git-blame-ignore-revs
              - .gitattributes
              - .gitignore
              - AUTHORS
              - Gemfile
              - Gemfile.lock
              - mruby-source.gemspec
mrbgems:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - mrbgems/**/*
oss-fuzz:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - oss-fuzz/**/*
